"""create initial tables

Revision ID: 36abf0e1dd74
Revises: 6f206fa800ed
Create Date: 2025-11-21 22:48:47.494425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36abf0e1dd74'
down_revision = '6f206fa800ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
