"""Initial schema from models

Revision ID: 6f206fa800ed
Revises: None
Create Date: 2025-10-24 05:08:04.729125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f206fa800ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('inci_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_index(op.f('ix_ingredients_inci_name'), 'ingredients', ['inci_name'], unique=True)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('skin_types',
    sa.Column('skin_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('skin_type_id')
    )
    op.create_index(op.f('ix_skin_types_type_name'), 'skin_types', ['type_name'], unique=True)
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
    )
    op.create_table('product_skin_types',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('skin_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['skin_type_id'], ['skin_types.skin_type_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'skin_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_skin_types')
    op.drop_table('product_ingredients')
    op.drop_index(op.f('ix_skin_types_type_name'), table_name='skin_types')
    op.drop_table('skin_types')
    op.drop_table('products')
    op.drop_index(op.f('ix_ingredients_inci_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
